title: Best Practices
email: ""
description: ""
baseurl: ""
url: "http://yourdomain.com"
repo: "https://github.com/dereknutile/best-practices"

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
