title: Web Development Best Practices
shortTitle: WDBP
email: ""
description: ""
baseurl: ""
url: "http://wdbp.github.io/"
repo: "https://github.com/wdbp"
contact: '<a href="http://dereknutile.com/" target="_blank">Derek Nutile</a>'

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
